name: webcamo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.3
  permission_handler: ^11.4.0
  wakelock_plus: ^1.4.0
  path_provider: ^2.1.2
  flutter_webrtc: ^1.2.0
  network_info_plus: ^7.0.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3
  url_launcher: ^6.3.0
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^3.0.3
  flutter_image_compress: ^2.3.0
  record: ^6.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  # This tells the package to generate icons for Android
  android: true 

  # This tells the package to generate icons for iOS
  ios: true

  # This is the path to your master icon file
  image_path: "assets/logos/webcamo-without-bg.png" 

  # This creates a special version for Android 12+ (adaptive icons)
  adaptive_icon_background: "assets/logos/icon-bg.png" # (Optional) A background color for Android
  adaptive_icon_foreground: "assets/logos/webcamo-without-bg.png" # (Optional) A background color for Android


flutter:
  uses-material-design: true

  assets:
      - assets/logos/
      - assets/images/
# Add this entire block at the end of the file
